bind r source-file ~/.tmux.conf

# Vim-like windows splitting
bind v split-window -h
bind s split-window

# Vim-like hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable mouse suppor
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1

# Match pane border with neovim window border
set -g pane-border-style "fg=#8aadf4"
set -g pane-active-border-style "fg=#8aadf4"

# Match status bar with neovim's status line
set -g status-position top
set -g status-style "bg=#1e2030,fg=#cad3f5"

# Match session name with neovim's mode indicator
set -g status-left "#[bg=#8aadf4,fg=#24273a,bold] #S #[bg=#1e2030,fg=#8aadf4] "
set -g status-left-length 40
